#!/usr/bin/env python3
"""
Render today's motivation card as a shareable PNG poster.

Reads data/daily.json (generated by generator/daily.py), fetches the headline
image, and draws a 1080x1350 (portrait 9:12, Telegram-friendly) card with the
quote, author, theme and date. Output: data/poster_<date>.png

Usage:
  venv/bin/python generator/render_poster.py [--date YYYY-MM-DD] [--out PATH]
"""
import argparse, json, os, sys, textwrap, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DAILY = ROOT / "data" / "daily.json"

# --- config (tweak freely) ---------------------------------------------
SIZE = (1080, 1350)               # portrait 9:12 -> nice for Telegram
BG_TOP = (17, 20, 30)             # near-black blue
BG_BOT = (26, 30, 44)
IMG_AREA = (60, 60, 1020, 660)    # where the photo sits (x0,y0,x1,y1)
ACCENT = (233, 196, 106)          # gold
TEXT = (236, 239, 246)            # near-white
MUTED = (140, 146, 164)
FONT_DIR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_BOLD_DIR = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def load_fonts():
    from PIL import ImageFont  # imported lazily (inside venv)
    def f(path, size):
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            return ImageFont.load_default()
    return {
        "theme": f(FONT_BOLD_DIR, 46),
        "date": f(FONT_DIR, 40),
        "quote": f(FONT_DIR, 66),
        "author": f(FONT_BOLD_DIR, 52),
        "footnote": f(FONT_DIR, 36),
    }


def fetch_image(url, dst):
    """Download the card's background photo into data/_img cache."""
    Path(dst).parent.mkdir(parents=True, exist_ok=True)
    if os.path.exists(dst):
        return dst
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (motivation-poster/1.0)"})
    with urllib.request.urlopen(req, timeout=40) as r, open(dst, "wb") as f:
        f.write(r.read())
    return dst


def wrap(text, font, max_w, draw):
    """word-wrap using font metrics"""
    words = text.split()
    lines, cur = [], ""
    for w in words:
        test = (cur + " " + w).strip()
        if draw.textlength(test, font=font) <= max_w:
            cur = test
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines or [text]


def render(entry, out_path):
    from PIL import Image, ImageDraw, ImageFilter

    # --- background gradient ---
    img = Image.new("RGB", SIZE)
    draw = ImageDraw.Draw(img)
    h = SIZE[1]
    for y in range(h):
        t = y / h
        row = tuple(int(BG_TOP[i] + (BG_BOT[i] - BG_TOP[i]) * t) for i in range(3))
        draw.line([(0, y), (SIZE[0], y)], fill=row)

    fonts = load_fonts()

    # --- photo ---
    img_path = fetch_image(entry["image"], ROOT / "data" / "_img" / f"{entry['date']}.jpg")
    try:
        photo = Image.open(img_path).convert("RGB")
        # cover-crop into IMG_AREA (keeps proportions, no distortion)
        box_w, box_h = IMG_AREA[2] - IMG_AREA[0], IMG_AREA[3] - IMG_AREA[1]
        scale = max(box_w / photo.width, box_h / photo.height)
        nw, nh = round(photo.width * scale), round(photo.height * scale)
        photo = photo.resize((nw, nh), Image.LANCZOS)
        left = (nw - box_w) // 2
        top = (nh - box_h) // 2
        photo = photo.crop((left, top, left + box_w, top + box_h))
        img.paste(photo, (IMG_AREA[0], IMG_AREA[1]))
        # thin accent border under the photo
        draw.rectangle((IMG_AREA[0], IMG_AREA[1], IMG_AREA[2], IMG_AREA[3]),
                       outline=ACCENT, width=3)
    except Exception as e:
        print(f"[render] photo fallback: {e}", file=sys.stderr)
        draw.rectangle((IMG_AREA[0], IMG_AREA[1], IMG_AREA[2], IMG_AREA[3]),
                       outline=ACCENT, width=3)

    # --- headline text over the photo (lower strip of IMG_AREA) ---
    # theme tag top-left inside photo
    theme = entry.get("theme", "").upper()
    draw.text((IMG_AREA[0] + 26, IMG_AREA[1] + 18), theme, font=fonts["theme"], fill=ACCENT)
    date_txt = entry["date"]
    draw.text((IMG_AREA[2] - draw.textlength(date_txt, font=fonts["date"]) - 26,
               IMG_AREA[1] + 18), date_txt, font=fonts["date"], fill=MUTED)

    # --- quote block (centered, below the photo, upper-middle of lower area) ---
    lang = entry.get("lang", "en")
    quote_text = entry[lang]
    author = entry.get("author", "")
    max_qw = SIZE[0] - 160
    qlines = wrap(quote_text, fonts["quote"], max_qw, draw)
    # widen to make sure long quotes fit: cap at 6 lines
    if len(qlines) > 6:
        qlines = qlines[:6]
    line_h = 92
    base_y = IMG_AREA[3] + 60
    for i, ln in enumerate(qlines):
        w = draw.textlength(ln, font=fonts["quote"])
        x = (SIZE[0] - w) // 2
        draw.text((x, base_y + i * line_h), ln, font=fonts["quote"], fill=TEXT)
    q_bottom = base_y + len(qlines) * line_h

    # --- author ---
    author_txt = f"— {author}"
    aw = draw.textlength(author_txt, font=fonts["author"])
    draw.text(((SIZE[0] - aw) // 2, q_bottom + 30), author_txt, font=fonts["author"], fill=ACCENT)

    # --- footnote pinned to the bottom ---
    foot = "Daily Motivation · every day a quote matched to the news"
    fw = draw.textlength(foot, font=fonts["footnote"])
    draw.text(((SIZE[0] - fw) // 2, SIZE[1] - 70), foot, font=fonts["footnote"], fill=MUTED)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    img.save(out_path, "PNG")
    print(out_path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--date", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--lang", default="en", choices=["en", "ru"])
    args = ap.parse_args()

    entry = json.load(open(DAILY))
    if args.date and entry.get("date") != args.date:
        # allow rendering a specific date from history if present
        print(f"[render] daily.json is {entry.get('date')}, --date {args.date} ignored (no archive yet)", file=sys.stderr)
    entry["lang"] = args.lang
    date = entry.get("date", "today")
    out = args.out or str(ROOT / "data" / f"poster_{date}.png")
    render(entry, out)


if __name__ == "__main__":
    main()